### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by hsvgbkhgbv** [semitable/robotic-warehouse#10]
>>> env = gym.make("rware-tiny-2ag-v1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jianhong/anaconda3/envs/mansa/lib/python3.7/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/home/jianhong/anaconda3/envs/mansa/lib/python3.7/site-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
  File "/home/jianhong/anaconda3/envs/mansa/lib/python3.7/site-packages/gym/envs/registration.py", line 140, in make
    env = cls(**_kwargs)
  File "/home/jianhong/anaconda3/envs/mansa/lib/python3.7/site-packages/rware/warehouse.py", line 247, in __init__
    self._use_slow_obs()
  File "/home/jianhong/anaconda3/envs/mansa/lib/python3.7/site-packages/rware/warehouse.py", line 359, in _use_slow_obs
    for _ in range(self.n_agents)
  File "/home/jianhong/anaconda3/envs/mansa/lib/python3.7/site-packages/rware/warehouse.py", line 359, in <listcomp>
    for _ in range(self.n_agents)
  File "/home/jianhong/anaconda3/envs/mansa/lib/python3.7/site-packages/gym/spaces/multi_binary.py", line 41, in __init__
    assert (np.asarray(input_n) > 0).all(), "n (counts) have to be positive"
AssertionError: n (counts) have to be positiv

**Comment by hsvgbkhgbv** [comment]
I am not sure why this error would happen.

**Comment by semitable** [comment]
Hi!
Could you try downgrading to gym==0.21 ?
I think gym broke a few things (again). I'll get to fixing for the latest version soon, but for now please try pip install gym==0.21.0

**Comment by aowen87** [comment]
I'm also encountering this issue. Any idea on an ETA for a fix?

**Comment by semitable** [comment]
@aowen87 Have you tried the solution above (downgrading to 0.21)?

**Comment by aowen87** [comment]
> @aowen87 Have you tried the solution above (downgrading to 0.21)?

Downgrading works, but I have some package dependencies that want a more recent version. It's not a big deal to remove the other packages for now. I'm just curious if there's an ETA for a longer term fix.

**Comment by aowen87** [comment]
Sounds good. Thanks!
