### ISSUE TITLE
Cannot run the basic program

### ISSUE THREAD

**Issue by Arseni1919** [semitable/robotic-warehouse#15]
Is this bug or I do something wrong?
The code from your README.md file..
```python
import gym
import rware
env = gym.make("rware-tiny-2ag-v1")
obs = env.reset()  # a tuple of observations

actions = env.action_space.sample()  # the action space can be sampled
print(actions)  # (1, 0)
n_obs, reward, done, info = env.step(actions)

print(done)    # [False, False]
print(reward)  # [0.0, 0.0]
env.render()
```

The output:
```
Traceback (most recent call last):
  File "/Users/perchik/PycharmProjects/Try_OpenAI_GYM/main.py", line 3, in <module>
    env = gym.make("rware-tiny-2ag-v1")
  File "/Users/perchik/opt/anaconda3/envs/Try_OpenAI_GYM/lib/python3.10/site-packages/gym/envs/registration.py", line 662, in make
    env = env_creator(**_kwargs)
  File "/Users/perchik/opt/anaconda3/envs/Try_OpenAI_GYM/lib/python3.10/site-packages/rware/warehouse.py", line 247, in __init__
    self._use_slow_obs()
  File "/Users/perchik/opt/anaconda3/envs/Try_OpenAI_GYM/lib/python3.10/site-packages/rware/warehouse.py", line 313, in _use_slow_obs
    [
  File "/Users/perchik/opt/anaconda3/envs/Try_OpenAI_GYM/lib/python3.10/site-packages/rware/warehouse.py", line 344, in <listcomp>
    "local_message": spaces.MultiBinary(
  File "/Users/perchik/opt/anaconda3/envs/Try_OpenAI_GYM/lib/python3.10/site-packages/gym/spaces/multi_binary.py", line 45, in __init__
    assert (np.asarray(input_n) > 0).all()  # n (counts) have to be positive
AssertionError
```

Why so? Can you help? 
Thanks in advance

**Comment by semitable** [comment]
duplicate of #13

**Comment by semitable** [comment]
and #10
