### ISSUE TITLE
Environment breaks down when an agent delivers a shelf

### ISSUE THREAD

**Issue by blurry-mood** [semitable/robotic-warehouse#6]
Hi, 
I am getting this error the moment an agent delivers a shelf to the predesignated location.

Here's a full stack of the error:
```
Traceback (most recent call last):
  File "/home/ayoub/Desktop/Projects/RL-algorithms/simulations/qlearning/qlearning.py", line 96, in <module>
    test_robot_warehouse()
  File "/home/ayoub/Desktop/Projects/RL-algorithms/simulations/qlearning/qlearning.py", line 81, in test_robot_warehouse
    states, rewards, done, info = env.step(actions)
  File "/home/ayoub/Desktop/Projects/RL-algorithms/venv/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 11, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/ayoub/Desktop/Projects/RL-algorithms/venv/lib/python3.9/site-packages/rware/warehouse.py", line 606, in step
    new_request = np.random.choice(
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

Here's the environment configuration:
`env = gym.make("rware:rware-tiny-2ag-v1", max_steps=MAX_STEPS, n_agents=N_AGENTS, request_queue_size=32)`

I suspect the bug is ignited because the queue size equals the number of shelves in the configuration, so when one is delivered this line fails to catch that exception (inside `warehouse.py`) since the list is empty:
```
new_request = np.random.choice(
                list(set(self.shelfs) - set(self.request_queue))
            )
```

**Comment by semitable** [comment]
Hi @blurry-mood 
Thanks for this report. You are right, 32 is the total number of shelves - but when a new request is being sampled, the one that has just been delivered is blocked from being picked (otherwise the agent would just need to stay put collecting rewards at every timestep).

So I guess for `tiny`, the max request size should be 31. 

It would be in order to add a warning/error when creating an environment with such a configuration. I will add that after the holidays!

Thanks!

**Comment by MosesChuka** [comment]
Hey guys, Please can anyone help?
Am getting this error as I try to update the sample action for Qlearning algorithm.



Traceback (most recent call last):
  File "/Users/mcmoses/PycharmProjects/Reinforcement_Learning_Tutorial_Edureka/venv/Mapping shortest part.py", line 119, in <module>
    action = sample_next_action(available_act)
  File "/Users/mcmoses/PycharmProjects/Reinforcement_Learning_Tutorial_Edureka/venv/Mapping shortest part.py", line 82, in sample_next_action
    next_action = (np.random.choice(available_act, 1))
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken


The function I defined for sample update is below

def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act, 1))
    return next_action



Please how do I resolve this issue?

**Comment by semitable** [comment]
Hi @MosesChuka,
Please open a new issue. Yours seems unrelated to this one. Also, I don't think this code even originates from the robotic warehouse? Are you sure it's where you wanted to post this?
